[package]
name = "madsim"
version = "0.2.0-alpha.2"
edition = "2021"
authors = ["Runji Wang <wangrunji0408@163.com>"]
description = "Deterministic Simulator for distributed systems."
readme = "../README.md"
homepage = "https://github.com/madsys-dev/madsim"
repository = "https://github.com/madsys-dev/madsim"
license = "Apache-2.0"
keywords = ["distributed-systems", "async", "deterministic", "simulation"]
categories = ["asynchronous", "simulation"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["macros", "logger", "rpc"]
sim = ["naive-timer", "async-task", "ahash", "toml", "downcast-rs"]
ucx = ["async-ucx", "lazy_static"]
rpc = ["bincode"]
macros = ["madsim-macros", "tokio/macros"]
logger = ["env_logger"]
erpc = ["rpc", "mad_rpc", "erased-serde"]

[dependencies]
ahash = { version = "0.7", optional = true }
async-task = { version = "4", optional = true }
async-ucx = { version = "0.1", features = ["event"], optional = true }
bincode = { version = "1", optional = true }
bytes = "1"
downcast-rs = { version = "1.2", default-features = false, optional = true }
env_logger = { version = "0.9", optional = true }
futures = "0.3"
lazy_static = { version = "1.4", optional = true }
log = "0.4"
madsim-macros = { version = "0.2.0-alpha.2", path = "../madsim-macros", optional = true }
naive-timer = { version = "0.2", optional = true }
rand = { version = "0.8", features = ["small_rng"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt", "fs", "net", "time", "io-util", "sync"] }
tokio-util = { version = "0.7", features = ["codec"] }
toml = { version = "0.5", optional = true }
# mad_rpc = { path = "../../madrpc/madrpc", optional = true }
mad_rpc = { git = "https://github.com/madsys-dev/madrpc", optional = true }
erased-serde = { version = "0.3", optional = true }

[dev-dependencies]
criterion = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
structopt = "0.3"

[[bench]]
name = "rpc"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
